remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Landing space of Pavel Cherkashin
description: Strategic and monetary advice for your startup
